### ISSUE TITLE
上拉加载更多

### ISSUE THREAD

**Issue by jiabaofeng** [xingda920813/SimpleRecyclerView#4]
希望博主能够加上上拉加载更多效果，自定义view入口，提供一个setLoaddingFooter（View view）
有时候需要自定义加载更多样式。
这个库已经很完美了，包含了emptyView。loadingview，loadingMore了。谢谢博主。以上是我使用体验。

**Comment by xingda920813** [comment]
1.6.0 版本增加了自定义 LoadingView 选项. Adapter.setCustomProgressView(View customProgressView).
